### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by aalemayhu**
* Trying to fix the home tap again (note: not sure if it fixes the issue, but nothing is breaking locally)
* Fix 404 for /tags link
* Use links in the tags page
* Fix markdown typo
* Replace broken link

### CODE REVIEW

**Comment by aalemayhu** [comment]
Hmm, I forgot to fix urls for tags that have spaces in them. Will trying using `slugify` and drop the work in progress prefix later.

**Comment by aalemayhu** [comment]
Dropping the `slugify`, the browser encodes the URLs properly. Tested via localhost with desktop Safari and Chrome also on iOS Safari.

**Comment by 3lvis** [comment]
Thanks Alexander!

**Comment by aalemayhu** [comment]
@3lvis thanks for merging this, but found it actually breaks stuff. I will follow up with a new pull request unless you want to revert all the changes. I have setup a own staging area on `http://tech.finn.xdp.no` to verify it actually works this time and will open pr after testing my changes properly.

Thanks.

**Comment by aalemayhu** [comment]
Actually nothing new broke, it was just my local setup that was rendering the page different. The links still don't work though, opened pr with potential fix https://github.com/finn-no/tech.finn.no/pull/51

but still not sure if fixed on tech.finn.no.

**Pull request merged**
